# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
  
target 'Community' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  # Pods for Community

  target 'CommunityTests' do
    # Pods for testing
  end

end

target 'CommunityExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommunityExample

end
